version: '3'
services:
  api:
    build:
      context: ./
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod # --smallfiles --logpath=/dev/null # --quiet
    